// UI copy for Test Device Lockscreens.
export const strings = {
  appName: 'Test Device Lockscreens',
  appShortName: 'Lockscreens',
  appTagline: 'Label this phone’s lockscreen',

  loading: {
    title: 'Preparing Lockscreens',
    body: 'Opening your local workspace…',
  },

  notFound: {
    title: 'Screen not found',
    body: 'That address does not match anything in Lockscreens.',
  },

  start: {
    title: 'Make a lockscreen that identifies this device',
    subtitle:
      'Add the details people need, preview the result, then set it from Photos. Everything stays on this device.',
    new: 'Create a lockscreen',
    continue: 'Continue your Draft',
    browse: 'Browse saved Devices',
    continueHint: 'Your last Draft is saved on this device.',
    steps: [
      { title: 'Add a Label', body: 'Give this device a name people can recognize.' },
      { title: 'Add Notes', body: 'Write the details that should appear on the Wallpaper.' },
      { title: 'Save to Photos', body: 'Then open it in Photos and choose Use as Wallpaper.' },
    ],
  },

  browse: {
    title: 'On this phone',
    empty: 'No devices yet. Start a new one.',
    edit: 'Edit',
    duplicate: 'Duplicate',
    delete: 'Delete',
    back: 'Back',
    confirmDelete: 'Delete this device?',
  },

  editor: {
    titleNew: 'New device',
    titleEdit: 'Edit device',
    label: 'Label',
    notes: 'Notes',
    notesHint:
      'Write the details that should appear on the Wallpaper. Start a line with # or ## for a Heading.',
    formatting: 'Formatting',
    bold: 'Bold',
    italic: 'Italic',
    strike: 'Strikethrough',
    code: 'Inline code',
    heading: 'Heading',
    phoneInfo: 'Phone info',
    phoneInfoModel: 'Model',
    phoneInfoOS: 'OS',
    phoneInfoAdd: 'Add',
    phoneInfoAddAll: 'Add all',
    phoneInfoDetecting: 'Detecting…',
    phoneInfoEmpty: 'Nothing detected on this browser',
    platform: 'Platform',
    platformInferred: 'Inferred from this phone',
    platformOverride: 'Override',
    exportSize: 'Export size',
    exportSizeAuto: 'Auto',
    exportSizeCustom: 'Custom',
    customizeExport: 'Customize export',
    detectedAutomatically: 'Detected automatically',
    autoSize: 'Auto size',
    customized: 'Customized',
    width: 'Width',
    height: 'Height',
    encoding: 'File',
    encodingQuality: 'Quality',
    encodingSize: 'Size',
    encodingQualityHint: 'PNG — sharpest',
    encodingSizeHint: 'JPEG — smaller file',
    saveToPhotos: 'Save to Photos',
    saveDevice: 'Save Device',
    download: 'Download',
    applyHint: 'Choose Save Image in the share sheet, then Photos → Use as Wallpaper',
    preview: 'Live preview',
    back: 'Back',
    labelRequired: 'Label is required',
    deviceSaved: 'Device saved',
    imageDownloaded: 'Image downloaded',
    imageDownloadedHint: 'Open it in Photos → Use as Wallpaper',
    imageFailed: 'Could not create the image',
  },

  install: {
    title: 'Keep Lockscreens on this device',
    body: 'Add the app to your Home Screen for quick access, offline use, and more reliable Drafts.',
    steps: 'Tap Share, then “Add to Home Screen”.',
    androidBody: 'Install the app for quick access, offline use, and more reliable Drafts.',
    androidSteps: 'Use the install prompt to add it to your Home Screen.',
    install: 'Install app',
    dismiss: 'Maybe later',
  },
} as const
