/* AUTO-GENERATED by scripts/generate-theme.ts. Do not edit directly. */
export const generatedThemeCss =
  ':root {\n    --space-0: 0;\n    --space-3xs: clamp(0.25rem, 0.21rem + 0.19vw, 0.375rem);\n    --space-2xs: clamp(0.5rem, 0.42rem + 0.37vw, 0.75rem);\n    --space-xs: clamp(0.75rem, 0.67rem + 0.37vw, 1rem);\n    --space-sm: clamp(1rem, 0.83rem + 0.74vw, 1.5rem);\n    --space-md: clamp(1.5rem, 1.33rem + 0.74vw, 2rem);\n    --space-lg: clamp(2rem, 1.67rem + 1.48vw, 3rem);\n    --space-xl: clamp(3rem, 2.50rem + 2.22vw, 4.5rem);\n    --space-xxl: clamp(4.5rem, 3.67rem + 3.70vw, 7rem);\n    --space-xs-sm: clamp(0.75rem, 0.50rem + 1.11vw, 1.5rem);\n    --space-sm-md: clamp(1rem, 0.67rem + 1.48vw, 2rem);\n    --space-md-lg: clamp(1.5rem, 1.00rem + 2.22vw, 3rem);\n    --space-lg-xl: clamp(2rem, 1.17rem + 3.70vw, 4.5rem);\n    --font-size-body: clamp(0.9375rem, 0.90rem + 0.19vw, 1.0625rem);\n    --font-size-small: clamp(0.8125rem, 0.79rem + 0.09vw, 0.875rem);\n    --font-size-h3: clamp(1.25rem, 1.13rem + 0.56vw, 1.625rem);\n    --font-size-h2: clamp(1.625rem, 1.42rem + 0.93vw, 2.25rem);\n    --font-size-h1: clamp(2.125rem, 1.67rem + 2.04vw, 3.5rem);\n    --font-size-display: clamp(2.75rem, 2.17rem + 2.59vw, 4.5rem);\n    --leading-tight: 1.15;\n    --leading-standard: 1.5;\n    --leading-loose: 1.7;\n    --font-weight-regular: 400;\n    --font-weight-medium: 500;\n    --font-weight-semibold: 600;\n    --font-weight-bold: 700;\n    --viewport-min: 22.5rem;\n    --viewport-max: 90rem;\n}'

export const fluidSpace = {
  '3xs': 'clamp(0.25rem, 0.21rem + 0.19vw, 0.375rem)',
  '2xs': 'clamp(0.5rem, 0.42rem + 0.37vw, 0.75rem)',
  xs: 'clamp(0.75rem, 0.67rem + 0.37vw, 1rem)',
  sm: 'clamp(1rem, 0.83rem + 0.74vw, 1.5rem)',
  md: 'clamp(1.5rem, 1.33rem + 0.74vw, 2rem)',
  lg: 'clamp(2rem, 1.67rem + 1.48vw, 3rem)',
  xl: 'clamp(3rem, 2.50rem + 2.22vw, 4.5rem)',
  xxl: 'clamp(4.5rem, 3.67rem + 3.70vw, 7rem)',
  'xs-sm': 'clamp(0.75rem, 0.50rem + 1.11vw, 1.5rem)',
  'sm-md': 'clamp(1rem, 0.67rem + 1.48vw, 2rem)',
  'md-lg': 'clamp(1.5rem, 1.00rem + 2.22vw, 3rem)',
  'lg-xl': 'clamp(2rem, 1.17rem + 3.70vw, 4.5rem)',
  zero: '0',
} as const

export const fluidType = {
  body: 'clamp(0.9375rem, 0.90rem + 0.19vw, 1.0625rem)',
  small: 'clamp(0.8125rem, 0.79rem + 0.09vw, 0.875rem)',
  h3: 'clamp(1.25rem, 1.13rem + 0.56vw, 1.625rem)',
  h2: 'clamp(1.625rem, 1.42rem + 0.93vw, 2.25rem)',
  h1: 'clamp(2.125rem, 1.67rem + 2.04vw, 3.5rem)',
  display: 'clamp(2.75rem, 2.17rem + 2.59vw, 4.5rem)',
} as const

export const leading = {
  tight: 1.15,
  standard: 1.5,
  loose: 1.7,
} as const
export const weights = {
  regular: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
} as const
