// Static client-only build for Netlify. Installable from the manifest; no
// service worker, so every launch loads current bytes from the network.
import { cpSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { renderToStream } from 'remix/ui/server'

import { assetServer } from '../app/assets.ts'
import { AppShell } from '../app/ui/app-shell.tsx'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const DIST = join(ROOT, 'dist')
const BUILD_ID = new Date()
  .toISOString()
  .replace(/[^0-9]/g, '')
  .slice(0, 14)

const CLIENT_ENTRIES = [
  'app/assets/entry.ts',
  'app/assets/install-hint.tsx',
  'app/assets/app.tsx',
  'app/ui/toast.tsx',
]

async function renderIndexHtml(): Promise<string> {
  const stream = renderToStream(<AppShell route="start" />, {
    async resolveClientEntry(entryId, component) {
      const { href, importMap, preloads } = await assetServer.getScriptEntry(entryId)

      return {
        href,
        importMap,
        preloads,
        exportName: entryId.split('#')[1] || component.name,
      }
    },
    onError(error) {
      throw error
    },
  })
  const html = await new Response(stream).text()
  return `<!doctype html>\n${html}`
}

function writeFileEnsured(absPath: string, data: Buffer | string) {
  mkdirSync(dirname(absPath), { recursive: true })
  writeFileSync(absPath, data)
}

// One-shot kill switch for the caching worker shipped by earlier builds.
//
// The app no longer uses a service worker: it is installable from the manifest
// alone and always loads from the network, so every launch is current. The old
// worker answered navigations cache-first, which could pin an installed device
// to a stale release that redeploying could not dislodge. Deleting `sw.js`
// would leave those installs controlled by it forever, so this worker ships in
// its place to unregister itself and drop the caches it created.
//
// It deliberately has no `fetch` handler, so requests bypass it entirely.
function cleanupWorkerSource(): string {
  return `// Generated by scripts/build.tsx — do not edit. Build ${BUILD_ID}.
self.addEventListener('install', () => {
  self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys()
      await Promise.all(keys.filter((k) => k.startsWith('tdl-')).map((k) => caches.delete(k)))
      await self.registration.unregister()

      // Move open windows onto network-served bytes. Nothing re-registers this
      // worker, so this runs once rather than looping.
      const clients = await self.clients.matchAll({ type: 'window' })
      for (const client of clients) client.navigate(client.url)
    })(),
  )
})
`
}

async function build() {
  console.log(`Building static client-only bundle (build ${BUILD_ID})…`)
  rmSync(DIST, { recursive: true, force: true })
  mkdirSync(DIST, { recursive: true })

  const html = await renderIndexHtml()
  writeFileEnsured(join(DIST, 'index.html'), html)
  console.log(`  index.html (${html.length} bytes)`)

  const assetUrls = await assetServer.getPreloads(CLIENT_ENTRIES)
  for (const assetUrl of assetUrls) {
    const res = await assetServer.fetch(new Request(new URL(assetUrl, 'http://build.local')))
    if (!res || !res.ok) {
      throw new Error(`Asset fetch failed for ${assetUrl}: ${res?.status}`)
    }
    const bytes = Buffer.from(await res.arrayBuffer())
    // Netlify decodes URL-encoded path segments before resolving static files.
    // Write package paths such as `%40remix-run` under their decoded name so
    // `/assets/npm/%40remix-run/...` resolves instead of falling through to
    // the SPA HTML fallback.
    writeFileEnsured(join(DIST, decodeURIComponent(assetUrl.replace(/^\//, ''))), bytes)
  }
  console.log(`  ${assetUrls.length} assets`)

  cpSync(join(ROOT, 'public'), DIST, { recursive: true })
  console.log('  copied public/')

  writeFileEnsured(join(DIST, 'version.json'), `${JSON.stringify({ buildId: BUILD_ID })}\n`)
  console.log(`  version.json (build ${BUILD_ID})`)

  writeFileEnsured(join(DIST, 'sw.js'), cleanupWorkerSource())
  console.log('  sw.js (cleanup worker — unregisters itself)')

  await assetServer.close?.()
  console.log('Done -> dist/')
}

build().catch((error) => {
  console.error(error)
  process.exit(1)
})
