// Static client-only build for Netlify / offline PWA.
import { cpSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { renderToStream } from 'remix/ui/server'

import { assetServer } from '../app/assets.ts'
import { AppShell } from '../app/ui/app-shell.tsx'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const DIST = join(ROOT, 'dist')
const BUILD_ID = new Date().toISOString().replace(/[^0-9]/g, '').slice(0, 14)

const CLIENT_ENTRIES = ['app/assets/entry.ts', 'app/assets/install-hint.tsx', 'app/assets/app.tsx']

const PUBLIC_PRECACHE = [
  '/manifest.webmanifest',
  '/favicon.svg',
  '/icons/icon-192.png',
  '/icons/icon-512.png',
  '/icons/icon-maskable-512.png',
  '/icons/apple-touch-icon.png',
]

async function renderIndexHtml(): Promise<string> {
  const stream = renderToStream(<AppShell />, {
    async resolveClientEntry(entryId, component) {
      const { href, importMap, preloads } = await assetServer.getScriptEntry(entryId)

      return {
        href,
        importMap,
        preloads,
        exportName: entryId.split('#')[1] || component.name,
      }
    },
    onError(error) {
      throw error
    },
  })
  const html = await new Response(stream).text()
  return `<!doctype html>\n${html}`
}

function writeFileEnsured(absPath: string, data: Buffer | string) {
  mkdirSync(dirname(absPath), { recursive: true })
  writeFileSync(absPath, data)
}

function serviceWorkerSource(precache: string[]): string {
  const list = JSON.stringify(precache, null, 2)
  return `// Generated by scripts/build.tsx — do not edit. Build ${BUILD_ID}.
const CACHE = 'tdl-${BUILD_ID}'
const PRECACHE = ${list}

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE)
      await Promise.allSettled(PRECACHE.map((url) => cache.add(url)))
      await self.skipWaiting()
    })(),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys()
      await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
      await self.clients.claim()
    })(),
  )
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  if (url.origin !== self.location.origin) return

  if (req.mode === 'navigate') {
    event.respondWith(
      (async () => {
        const cache = await caches.open(CACHE)
        const shell = (await cache.match('/index.html')) || (await cache.match('/'))
        if (shell) return shell
        try {
          return await fetch(req)
        } catch {
          return (await cache.match('/index.html')) || Response.error()
        }
      })(),
    )
    return
  }

  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached
      return fetch(req)
        .then((res) => {
          if (res.ok && res.type === 'basic') {
            const copy = res.clone()
            caches.open(CACHE).then((cache) => cache.put(req, copy))
          }
          return res
        })
        .catch(() => cached || Response.error())
    }),
  )
})
`
}

async function build() {
  console.log(`Building static client-only bundle (build ${BUILD_ID})…`)
  rmSync(DIST, { recursive: true, force: true })
  mkdirSync(DIST, { recursive: true })

  const html = await renderIndexHtml()
  writeFileEnsured(join(DIST, 'index.html'), html)
  console.log(`  index.html (${html.length} bytes)`)

  const assetUrls = await assetServer.getPreloads(CLIENT_ENTRIES)
  for (const assetUrl of assetUrls) {
    const res = await assetServer.fetch(new Request(new URL(assetUrl, 'http://build.local')))
    if (!res || !res.ok) {
      throw new Error(`Asset fetch failed for ${assetUrl}: ${res?.status}`)
    }
    const bytes = Buffer.from(await res.arrayBuffer())
    // Netlify decodes URL-encoded path segments before resolving static files.
    // Write package paths such as `%40remix-run` under their decoded name so
    // `/assets/npm/%40remix-run/...` resolves instead of falling through to
    // the SPA HTML fallback.
    writeFileEnsured(join(DIST, decodeURIComponent(assetUrl.replace(/^\//, ''))), bytes)
  }
  console.log(`  ${assetUrls.length} assets`)

  cpSync(join(ROOT, 'public'), DIST, { recursive: true })
  console.log('  copied public/')

  const precache = ['/', '/index.html', ...assetUrls, ...PUBLIC_PRECACHE]
  writeFileEnsured(join(DIST, 'sw.js'), serviceWorkerSource(precache))
  console.log(`  sw.js (${precache.length} precached entries)`)

  await assetServer.close?.()
  console.log('Done -> dist/')
}

build().catch((error) => {
  console.error(error)
  process.exit(1)
})
