import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

type RangeToken = { name: string; min: number; max: number }
type Viewports = { min: number; max: number }

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const tokensDir = join(root, 'design-tokens')
const outputPath = join(root, 'app/ui/generated-theme.ts')
const rootSize = 16

async function readJson<T>(name: string): Promise<T> {
  return JSON.parse(await readFile(join(tokensDir, name), 'utf8')) as T
}

function cssName(name: string) {
  return name
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
}

function rem(value: number) {
  return `${Number((value / rootSize).toFixed(4))}rem`
}

function fluidValue(min: number, max: number, viewports: Viewports) {
  if (min === max) return rem(min)
  const minRem = min / rootSize
  const maxRem = max / rootSize
  const minViewportRem = viewports.min / rootSize
  const maxViewportRem = viewports.max / rootSize
  const slope = (maxRem - minRem) / (maxViewportRem - minViewportRem)
  const intercept = minRem - minViewportRem * slope
  return `clamp(${rem(min)}, ${intercept.toFixed(2)}rem + ${(slope * 100).toFixed(2)}vw, ${rem(max)})`
}

function quote(value: string) {
  return JSON.stringify(value)
}

async function generate() {
  const [spacing, textSizes, leading, weights, viewports] = await Promise.all([
    readJson<RangeToken[]>('spacing.json'),
    readJson<RangeToken[]>('text-sizes.json'),
    readJson<Record<string, number>>('text-leading.json'),
    readJson<Record<string, number>>('text-weights.json'),
    readJson<Viewports>('viewports.json'),
  ])

  const spaceEntries = spacing.map(
    ({ name, min, max }) => [cssName(name), fluidValue(min, max, viewports)] as const,
  )
  const typeEntries = textSizes.map(
    ({ name, min, max }) => [cssName(name), fluidValue(min, max, viewports)] as const,
  )
  const object = (entries: readonly (readonly [string, string])[]) =>
    entries
      .map(([name, value]) => {
        const key = /^[a-zA-Z_$][\w$]*$/.test(name) ? name : quote(name)
        return `  ${key}: ${quote(value)}`
      })
      .join(',\n')
  const css = [
    `    --space-0: 0;`,
    ...spaceEntries.map(([name, value]) => `    --space-${name}: ${value};`),
    ...typeEntries.map(([name, value]) => `    --font-size-${name}: ${value};`),
    ...Object.entries(leading).map(([name, value]) => `    --leading-${cssName(name)}: ${value};`),
    ...Object.entries(weights).map(
      ([name, value]) => `    --font-weight-${cssName(name)}: ${value};`,
    ),
    `    --viewport-min: ${rem(viewports.min)};`,
    `    --viewport-max: ${rem(viewports.max)};`,
  ].join('\n')

  const output = `/* AUTO-GENERATED by scripts/generate-theme.ts. Do not edit directly. */
export const generatedThemeCss = ${quote(`:root {\n${css}\n}`)}

export const fluidSpace = {
${object(spaceEntries)},
  zero: '0',
} as const

export const fluidType = {
${object(typeEntries)},
} as const

export const leading = ${JSON.stringify(leading, null, 2)} as const
export const weights = ${JSON.stringify(weights, null, 2)} as const
`

  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, output)
  console.log(`Generated ${outputPath}`)
}

await generate()
